### ISSUE TITLE
Basic sign in Node

### ISSUE THREAD

**Issue by pepoospina** [vemonet/nanopub-rs#8] opened 2024-04-05 15:31 UTC
Hi @vemonet, 

I created a simple repo to show you a behavior I'm observing with `@nanopub/sign` inside of NodeJS when runing the simplest possible flow:

```ts
const profile = new NpProfile(key, "", "", "");
const nanopub = new Nanopub(rdf);
const signed = nanopub.sign(profile);

console.log({ profile, nanopub, signed });
console.log({ profile, nanopub: nanopub.info(), signed: signed.info() });
```

I created a minimal reproduction at https://github.com/Common-SenseMakers/nanopubs-test

If I run
```
yarn install
yarn start
```

I get the Error 
```
Error: null pointer passed to rust`
``` 
when calling `nanopub.info()`.

Maybe we are missing something? Do you mind taking a look and sharing your thoughts? 
thanks!

**Comment by vemonet** [comment] 2024-04-17 16:54
Hi @pepoospina, I do not manage to reproduce it when running the with jest, are you sure you are using the latest version `0.1.3` ?

It looks a lot similar to the issue you had previously, the object was consumed. Does this work if you just try to print the nanopubs info and not the profile?

**Comment by pepoospina** [comment] 2024-05-30 09:07
Hi @vemonet, we are adding the signing process to the backend (NodeJS) so that we can sign NPs both from the frontend and the backend.

In the frontend, it works perfectly. But on the backend, I'm seeing some issues. 

On our code, I get 
```ts
Error: expected instance of NpProfile
```

But the profile object I send was build with `NpProfile` without errors.

And if I try with the [simple test repo](https://github.com/Common-SenseMakers/nanopubs-test), I still get the `null pointer passed to rust` error.

Two questions:
1) Do you have any idea of what might be causing the NpProfile to not be detected as a valid profile when signing?
2) Did you try runing the sample repo using `yarn start` instead of jest?

Thanks

**Comment by vemonet** [comment] 2024-05-30 15:36
Hi @pepoospina , I had a check and find out that the problem is due to calling the `nanopub.info()` method after signing. Basically the object is "moved" from `nanopub` to `signed` during the signing process, so it is not available anymore in `nanopub` 

So right now the best would be to do instantiation and signing in one step (you can also do it in 2 steps, but don't try to use the `nanopub` object after signing, as it will be gone!):

```js
const signed = new Nanopub(rdf).sign(profile);
```

And you will need to recreate a new `Nanopub(rdf)` everytime you need a new one, would that work for you right now?

I agree that ideally we should also support in 2 steps as you are doing, e.g.:

```js
const nanopub = new Nanopub(rdf);
const signed = nanopub.sign(profile);
``` 

But I need to check a little bit what would be the best way to handle the 2 use cases (one step and 2 steps) without doing unnecessary copy of objects (there must be some design pattern to do this properly)


Note I also pushed a new version `0.1.4` that now support optional arguments for `NpProfile`, and add some checks on the passed arguments (e.g. orcid URL conform)

So you should instantiate NpProfile with `NpProfile(key);` if you just want to provide the private key

**Comment by pepoospina** [comment] 2024-05-30 16:31
Cool @vemonet . I will try doing it in one step. 

Regarding the orcid URL conform. We are not using orcid for the moment and I send an empty string. Would that be a problem?

**Comment by vemonet** [comment] 2024-05-31 06:57
Yes with the new version you can just do

```
const profile = new NpProfile(key);
```

**Comment by vemonet** [comment] 2024-10-29 15:17
I see this is now used in production here: https://github.com/Common-SenseMakers/sensemakers/blob/0377c01d0e46146dfb64ab4462c08e2cc6836b8a/app/webapp/src/shared/utils/nanopub.sign.util.ts#L1 

I'll close this issue then

**Closed by vemonet** 2024-10-29 15:17 UTC
